{{- if and (not .Values.existingSecret) .Values.masterToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "aperio-server.fullname" .) }}
  labels:
    {{- include "aperio-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tokenKey }}: {{ .Values.masterToken | quote }}
{{- end -}}
