#!/usr/bin/env bash
# Renders the Homebrew formulae and Scoop manifests for a release
# (planned_features #93).
#
#   packaging/render-manifests.sh <version-without-v> <dir-of-release-assets> <out-dir>
#
# The assets directory is the release job's `dist-pkg`, which already holds a
# `<file>.sha256` beside every artifact. Hashes are read from those rather than
# recomputed, so the formula and the checksum manifest can never disagree: they
# are the same number, read once.
#
# A separate script rather than a block inside the workflow, so it can be run
# against a published release's assets and the output inspected, which is how
# it was checked before it ever ran in CI.
set -euo pipefail

version="${1:?usage: render-manifests.sh <version> <assets-dir> <out-dir>}"
assets="${2:?}"
out="${3:?}"
repo="${APERIO_REPO:-co3moz/aperio}"
base="https://github.com/${repo}/releases/download/v${version}"

mkdir -p "$out"

# The first field of `<file>.sha256`, which both shasum and sha256sum write as
# "<hash>  <name>".
#
# Found rather than addressed directly: in the release job the artifacts arrive
# under one subdirectory per build target, and locally they are usually a flat
# directory of downloaded assets. Searching covers both, and a name that
# matches twice is an error rather than a coin toss.
hash_of() {
  local file="$1"
  local found
  found="$(find "$assets" -type f -name "${file}.sha256" | sort)"
  if [ -z "$found" ]; then
    echo "missing ${file}.sha256 under ${assets}" >&2
    return 1
  fi
  if [ "$(printf '%s\n' "$found" | wc -l)" -gt 1 ]; then
    echo "several ${file}.sha256 under ${assets}:" >&2
    printf '%s\n' "$found" >&2
    return 1
  fi
  awk '{print $1; exit}' "$found"
}

for bin in aperio-client aperio-server; do
  case "$bin" in
    aperio-client)
      # Under 80 characters and not starting with the formula's own name:
      # `brew style` enforces both.
      desc="Expose a local backend or directory through an Aperio tunnel"
      ;;
    aperio-server)
      desc="Tunnel server that proxies visitor traffic to connected clients"
      ;;
  esac
  # aperio-client -> AperioClient, which is the class name Homebrew requires
  # for a formula file named aperio-client.rb.
  class="$(echo "$bin" | awk -F- '{printf "%s%s", toupper(substr($1,1,1)) substr($1,2), toupper(substr($2,1,1)) substr($2,2)}')"

  mac_arm="${bin}-aarch64-apple-darwin.tar.gz"
  mac_intel="${bin}-x86_64-apple-darwin.tar.gz"
  linux_arm="${bin}-aarch64-unknown-linux-musl.tar.gz"
  linux_intel="${bin}-x86_64-unknown-linux-musl.tar.gz"
  windows="${bin}-x86_64-pc-windows-msvc.zip"

  cat > "${out}/${bin}.rb" <<EOF
# typed: strict
# frozen_string_literal: true

# Generated by packaging/render-manifests.sh for v${version}. Do not edit by
# hand: the next release overwrites it.
class ${class} < Formula
  desc "${desc}"
  homepage "https://github.com/${repo}"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
      url "${base}/${mac_arm}"
      sha256 "$(hash_of "$mac_arm")"
    end
    on_intel do
      url "${base}/${mac_intel}"
      sha256 "$(hash_of "$mac_intel")"
    end
  end

  on_linux do
    on_arm do
      url "${base}/${linux_arm}"
      sha256 "$(hash_of "$linux_arm")"
    end
    on_intel do
      url "${base}/${linux_intel}"
      sha256 "$(hash_of "$linux_intel")"
    end
  end

  def install
    bin.install "${bin}"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/${bin} --version")
  end
end
EOF

  cat > "${out}/${bin}.json" <<EOF
{
  "version": "${version}",
  "description": "${desc}",
  "homepage": "https://github.com/${repo}",
  "license": "MIT",
  "architecture": {
    "64bit": {
      "url": "${base}/${windows}",
      "hash": "$(hash_of "$windows")"
    }
  },
  "bin": "${bin}.exe",
  "checkver": {
    "github": "https://github.com/${repo}"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/${repo}/releases/download/v\$version/${bin}-x86_64-pc-windows-msvc.zip"
      }
    },
    "hash": {
      "url": "\$url.sha256"
    }
  }
}
EOF
done

echo "rendered into ${out}:"
ls -1 "$out"
