//! The proxy handler driven end to end: what a visitor gets when nothing is
//! connected, what they get when something is, and the rate limits that refuse
//! them before either.

use super::super::tests::*;
use crate::protocol::TunnelMessage;
use crate::proxy::proxy_handler;
use crate::settings::{FailoverMode, LbStrategy, ServerConfig, SettingsOverrides};
use crate::state::{
  AppState, ClientHandle, ClientPerms, ConnectionState, DurationHistogram, ServerStats,
  TunnelResponse,
};
use axum::{
  body::Body,
  extract::{ConnectInfo, State, ws::Message},
  http::StatusCode,
};
use base64::Engine;
use std::collections::{HashMap, VecDeque};
use std::net::{IpAddr, Ipv4Addr, SocketAddr};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, AtomicUsize};
use std::time::{Duration, Instant};
use tokio::sync::{Mutex, mpsc, watch};

#[tokio::test]
pub(crate) async fn test_rate_limiting() {
  let config = ServerConfig {
    token: "test".to_string(),
    gateway_timeout: Duration::from_secs(1),
    gateway_response_timeout: Duration::from_secs(1),
    max_body_size: 1024,
    max_tunnels: 1,
    max_connections_per_service: 16,
    inspector: true,
    access_events: true,
    ip_limit_max: 2.0,
    ip_limit_refill: 0.0, // No refill for testing strict burst limit
    visitor_auth_block: None,
    visitor_auth: crate::visitor_auth::Policy::default(),
    trust_proxy: false,
    ignore_client_auth: false,
    real_ip_header: None,
    trusted_proxies: Vec::new(),
    admin_allowed_ips: Vec::new(),
    secure_cookies: false,
    require_hostname_bind: false,
    default_access: crate::settings::DefaultAccess::Allow,
    metrics_token: None,
    scaling_enabled: false,
    scaling_allow_http: false,
    scaling_allow_private: false,
    scaling_record_ttl: Duration::from_secs(3600),
    edge_token: None,
    edge_service_url: None,
    edge_entrypoints: Vec::new(),
    edge_cert_resolver: None,
    edge_include_offline: false,
    random_subdomain_suffix: None,
    client_down_threshold: Duration::from_secs(3600),
    tunnel_compression: false,
    custom_504_page: None,
    custom_503_page: None,
    lb_strategy: LbStrategy::RoundRobin,
    failover_mode: FailoverMode::Fail,
    failover_max_jumps: 2,
    failover_window: Duration::from_secs(15),
    failover_all_methods: false,
    retry_on_5xx: false,
    retry_statuses: Vec::new(),
    outlier_ejection: false,
    outlier_max_failures: 5,
    outlier_window: Duration::from_secs(30),
    outlier_eject: Duration::from_secs(30),
    cache_enabled: false,
    max_concurrent_requests: 100,
    max_ws_connections: 10_000,
    login_lockout_threshold: 5,
    login_lockout_secs: 60,
    audit_max_size: 10 * 1024 * 1024,
    audit_max_files: 3,
    ui_language: "en".to_string(),
    header_rules: Default::default(),
    static_routes: Default::default(),
    error_pages: Default::default(),
    route_limits: Default::default(),
    fallbacks: Default::default(),
    waf: Default::default(),
    maintenance_windows: Default::default(),
    alert_rules: Default::default(),
    denied_ips: Default::default(),
    identity_headers: false,
    visitor_identity_headers: false,
    access_log_sample_rate: 1.0,
    alternate_servers: Vec::new(),
    max_streams_per_ip: 0,
    otel_bridge: false,
    shutdown_drain: None,
    shutdown_drain_auto: false,
    shutdown_timeout: 10,
    request_id_enabled: true,
    request_id_header: "x-request-id".to_string(),
    request_id_trust_inbound: false,
    token_pinning: false,
    preview_noindex: false,
    cache_max_bytes: 64 * 1024 * 1024,
    cache_max_stale: 3600,
    stream_min_throughput: 0,
    stream_pause_bytes: 2 * 1024 * 1024,
    stream_resume_bytes: 512 * 1024,
    stream_backlog_limit: 16 * 1024 * 1024,
    outbound_policy: Default::default(),
  };

  let (client_connected_tx, _) = watch::channel(false);
  let state = AppState {
    clients: tokio::sync::RwLock::new(HashMap::new()),
    consumers: tokio::sync::Mutex::new(Default::default()),
    stream_counts: Arc::new(std::sync::Mutex::new(HashMap::new())),
    telemetry_tx: tokio::sync::mpsc::channel(1).0,
    pending_messages: Mutex::new(HashMap::new()),
    jwks_cache: Mutex::new(HashMap::new()),
    forward_auth_cache: Mutex::new(HashMap::new()),
    message_metrics: Default::default(),
    client_connected: client_connected_tx,
    connection_state: Mutex::new(ConnectionState {
      connected: false,
      last_disconnect: None,
    }),
    server_start_time: Instant::now(),
    pending_requests: Mutex::new(HashMap::new()),
    stats: Mutex::new(ServerStats {
      total_requests: 0,
      successful_requests: 0,
      failed_requests: 0,
      total_bytes_transferred: 0,
    }),
    recent_logs: Mutex::new(VecDeque::new()),
    traffic_tx: tokio::sync::broadcast::channel(16).0,
    events_tx: tokio::sync::broadcast::channel(16).0,
    config_store: std::sync::RwLock::new(Arc::new(config.clone())),
    config_env_defaults: Arc::new(config),
    settings_overrides: Mutex::new(SettingsOverrides::default()),
    settings_path: crate::test_support::test_temp_root()
      .join(format!("settings-{}.json", uuid::Uuid::new_v4())),
    dashboard_enabled: true,
    shutdown: watch::channel(false).0,
    active_proxied_requests: Arc::new(AtomicUsize::new(0)),
    active_ws_connections: Arc::new(AtomicUsize::new(0)),
    path_rr: Mutex::new(HashMap::new()),
    sessions: Mutex::new(test_session_store()),
    rate_limiter: Mutex::new(HashMap::new()),
    login_lockout: tokio::sync::Mutex::new(crate::auth::LockoutTracker::new(
      5,
      std::time::Duration::from_secs(60),
    )),
    token_rate: Mutex::new(HashMap::new()),
    token_daily_bytes: Mutex::new(HashMap::new()),
    token_seen_ips: Mutex::new(HashMap::new()),
    route_rate: Mutex::new(HashMap::new()),
    active_tunnel_count: AtomicUsize::new(0),
    ws_streams: Mutex::new(HashMap::new()),
    pending_upgrades: Mutex::new(HashMap::new()),
    token_store: Mutex::new(test_token_store()),
    admin_key_store: Mutex::new(test_admin_key_store()),
    inbox_store: Mutex::new(test_inbox_store()),
    users: Mutex::new(test_user_store()),
    response_streams: Mutex::new(HashMap::new()),
    captured_requests: Mutex::new(VecDeque::new()),
    audit: Mutex::new(test_audit_log()),
    persistent_stats: Mutex::new(test_stats_store()),
    webhook_deliveries: test_delivery_log(),
    scaling_store: Mutex::new(crate::test_support::test_scaling_store()),
    scaling_runtime: Mutex::new(crate::scaling::ScalingRuntime::default()),
    scaling_calls: crate::scaling::call_semaphore(),
    webhook_store: Mutex::new(test_webhook_store()),
    org_store: Mutex::new(test_org_store()),
    uptime: Mutex::new(test_uptime_store()),
    webauthn: None,
    webauthn_ceremonies: Mutex::new(crate::webauthn::WebauthnCeremonies::default()),
    oidc: None,
    org_oidc: Mutex::new(HashMap::new()),
    oidc_states: Mutex::new(HashMap::new()),
    tcp_streams: Mutex::new(HashMap::new()),
    udp_streams: Mutex::new(HashMap::new()),
    response_cache: Mutex::new(crate::cache::ResponseCache::default()),
    cache_inflight: std::sync::Mutex::new(std::collections::HashMap::new()),
    stage_stats: Mutex::new(crate::state::StageStats::default()),
    endpoint_stats: Mutex::new(crate::state::EndpointStats::default()),
    route_trends: Mutex::new(crate::state::RouteTrends::default()),
    activity: Mutex::new(crate::state::Activity::default()),
    maintenance: Mutex::new(std::collections::HashMap::new()),
    access_log: None,
    duration_histogram: DurationHistogram::default(),
    limit_counters: Default::default(),
  };

  let ip = IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1));

  // First request should pass
  assert!(state.check_rate_limit(ip).await);
  // Second request should pass
  assert!(state.check_rate_limit(ip).await);
  // Third request should be rate limited (max burst is 2.0)
  assert!(!state.check_rate_limit(ip).await);
}

#[tokio::test]
pub(crate) async fn test_proxy_handler_gateway_timeout_offline() {
  let config = ServerConfig {
    token: "test".to_string(),
    gateway_timeout: Duration::from_millis(100),
    gateway_response_timeout: Duration::from_millis(100),
    max_body_size: 1024,
    max_tunnels: 1,
    max_connections_per_service: 16,
    inspector: true,
    access_events: true,
    ip_limit_max: 100.0,
    ip_limit_refill: 10.0,
    visitor_auth_block: None,
    visitor_auth: crate::visitor_auth::Policy::default(),
    trust_proxy: false,
    ignore_client_auth: false,
    real_ip_header: None,
    trusted_proxies: Vec::new(),
    admin_allowed_ips: Vec::new(),
    secure_cookies: false,
    require_hostname_bind: false,
    default_access: crate::settings::DefaultAccess::Allow,
    metrics_token: None,
    scaling_enabled: false,
    scaling_allow_http: false,
    scaling_allow_private: false,
    scaling_record_ttl: Duration::from_secs(3600),
    edge_token: None,
    edge_service_url: None,
    edge_entrypoints: Vec::new(),
    edge_cert_resolver: None,
    edge_include_offline: false,
    random_subdomain_suffix: None,
    client_down_threshold: Duration::from_secs(3600),
    tunnel_compression: false,
    custom_504_page: None,
    custom_503_page: None,
    lb_strategy: LbStrategy::RoundRobin,
    failover_mode: FailoverMode::Fail,
    failover_max_jumps: 2,
    failover_window: Duration::from_secs(15),
    failover_all_methods: false,
    retry_on_5xx: false,
    retry_statuses: Vec::new(),
    outlier_ejection: false,
    outlier_max_failures: 5,
    outlier_window: Duration::from_secs(30),
    outlier_eject: Duration::from_secs(30),
    cache_enabled: false,
    max_concurrent_requests: 100,
    max_ws_connections: 10_000,
    login_lockout_threshold: 5,
    login_lockout_secs: 60,
    audit_max_size: 10 * 1024 * 1024,
    audit_max_files: 3,
    ui_language: "en".to_string(),
    header_rules: Default::default(),
    static_routes: Default::default(),
    error_pages: Default::default(),
    route_limits: Default::default(),
    fallbacks: Default::default(),
    waf: Default::default(),
    maintenance_windows: Default::default(),
    alert_rules: Default::default(),
    denied_ips: Default::default(),
    identity_headers: false,
    visitor_identity_headers: false,
    access_log_sample_rate: 1.0,
    alternate_servers: Vec::new(),
    max_streams_per_ip: 0,
    otel_bridge: false,
    shutdown_drain: None,
    shutdown_drain_auto: false,
    shutdown_timeout: 10,
    request_id_enabled: true,
    request_id_header: "x-request-id".to_string(),
    request_id_trust_inbound: false,
    token_pinning: false,
    preview_noindex: false,
    cache_max_bytes: 64 * 1024 * 1024,
    cache_max_stale: 3600,
    stream_min_throughput: 0,
    stream_pause_bytes: 2 * 1024 * 1024,
    stream_resume_bytes: 512 * 1024,
    stream_backlog_limit: 16 * 1024 * 1024,
    outbound_policy: Default::default(),
  };

  let (client_connected_tx, _) = watch::channel(false);
  let state = Arc::new(AppState {
    clients: tokio::sync::RwLock::new(HashMap::new()),
    consumers: tokio::sync::Mutex::new(Default::default()),
    stream_counts: Arc::new(std::sync::Mutex::new(HashMap::new())),
    telemetry_tx: tokio::sync::mpsc::channel(1).0,
    pending_messages: Mutex::new(HashMap::new()),
    jwks_cache: Mutex::new(HashMap::new()),
    forward_auth_cache: Mutex::new(HashMap::new()),
    message_metrics: Default::default(),
    client_connected: client_connected_tx,
    connection_state: Mutex::new(ConnectionState {
      connected: false,
      last_disconnect: None,
    }),
    // Set start time to 2 minutes ago to trigger immediate timeout
    server_start_time: Instant::now() - Duration::from_secs(120),
    pending_requests: Mutex::new(HashMap::new()),
    stats: Mutex::new(ServerStats {
      total_requests: 0,
      successful_requests: 0,
      failed_requests: 0,
      total_bytes_transferred: 0,
    }),
    recent_logs: Mutex::new(VecDeque::new()),
    traffic_tx: tokio::sync::broadcast::channel(16).0,
    events_tx: tokio::sync::broadcast::channel(16).0,
    config_store: std::sync::RwLock::new(Arc::new(config.clone())),
    config_env_defaults: Arc::new(config),
    settings_overrides: Mutex::new(SettingsOverrides::default()),
    settings_path: crate::test_support::test_temp_root()
      .join(format!("settings-{}.json", uuid::Uuid::new_v4())),
    dashboard_enabled: true,
    shutdown: watch::channel(false).0,
    active_proxied_requests: Arc::new(AtomicUsize::new(0)),
    active_ws_connections: Arc::new(AtomicUsize::new(0)),
    path_rr: Mutex::new(HashMap::new()),
    sessions: Mutex::new(test_session_store()),
    rate_limiter: Mutex::new(HashMap::new()),
    login_lockout: tokio::sync::Mutex::new(crate::auth::LockoutTracker::new(
      5,
      std::time::Duration::from_secs(60),
    )),
    token_rate: Mutex::new(HashMap::new()),
    token_daily_bytes: Mutex::new(HashMap::new()),
    token_seen_ips: Mutex::new(HashMap::new()),
    route_rate: Mutex::new(HashMap::new()),
    active_tunnel_count: AtomicUsize::new(0),
    ws_streams: Mutex::new(HashMap::new()),
    pending_upgrades: Mutex::new(HashMap::new()),
    token_store: Mutex::new(test_token_store()),
    admin_key_store: Mutex::new(test_admin_key_store()),
    inbox_store: Mutex::new(test_inbox_store()),
    users: Mutex::new(test_user_store()),
    response_streams: Mutex::new(HashMap::new()),
    captured_requests: Mutex::new(VecDeque::new()),
    audit: Mutex::new(test_audit_log()),
    persistent_stats: Mutex::new(test_stats_store()),
    webhook_deliveries: test_delivery_log(),
    scaling_store: Mutex::new(crate::test_support::test_scaling_store()),
    scaling_runtime: Mutex::new(crate::scaling::ScalingRuntime::default()),
    scaling_calls: crate::scaling::call_semaphore(),
    webhook_store: Mutex::new(test_webhook_store()),
    org_store: Mutex::new(test_org_store()),
    uptime: Mutex::new(test_uptime_store()),
    webauthn: None,
    webauthn_ceremonies: Mutex::new(crate::webauthn::WebauthnCeremonies::default()),
    oidc: None,
    org_oidc: Mutex::new(HashMap::new()),
    oidc_states: Mutex::new(HashMap::new()),
    tcp_streams: Mutex::new(HashMap::new()),
    udp_streams: Mutex::new(HashMap::new()),
    response_cache: Mutex::new(crate::cache::ResponseCache::default()),
    cache_inflight: std::sync::Mutex::new(std::collections::HashMap::new()),
    stage_stats: Mutex::new(crate::state::StageStats::default()),
    endpoint_stats: Mutex::new(crate::state::EndpointStats::default()),
    route_trends: Mutex::new(crate::state::RouteTrends::default()),
    activity: Mutex::new(crate::state::Activity::default()),
    maintenance: Mutex::new(std::collections::HashMap::new()),
    access_log: None,
    duration_histogram: DurationHistogram::default(),
    limit_counters: Default::default(),
  });

  // A fresh install (no client ever, no traffic ever) redirects the bare
  // root to the dashboard instead of showing a 504.
  let response = proxy_handler(
    State(state.clone()),
    ConnectInfo(SocketAddr::from(([127, 0, 0, 1], 12345))),
    axum::extract::Request::new(Body::empty()),
  )
  .await;
  assert_eq!(response.status(), StatusCode::TEMPORARY_REDIRECT);
  assert_eq!(
    response
      .headers()
      .get("location")
      .unwrap()
      .to_str()
      .unwrap(),
    "/aperio"
  );

  // Any other path still answers 504 while no client is connected.
  let mut req = axum::extract::Request::new(Body::empty());
  *req.uri_mut() = "/hello".parse().unwrap();
  let response = proxy_handler(
    State(state),
    ConnectInfo(SocketAddr::from(([127, 0, 0, 1], 12345))),
    req,
  )
  .await;
  assert_eq!(response.status(), StatusCode::GATEWAY_TIMEOUT);
}

#[tokio::test]
pub(crate) async fn test_proxy_handler_success() {
  let config = ServerConfig {
    token: "test".to_string(),
    gateway_timeout: Duration::from_millis(200),
    gateway_response_timeout: Duration::from_millis(500),
    max_body_size: 1024,
    max_tunnels: 2,
    max_connections_per_service: 16,
    inspector: true,
    access_events: true,
    ip_limit_max: 100.0,
    ip_limit_refill: 10.0,
    visitor_auth_block: None,
    visitor_auth: crate::visitor_auth::Policy::default(),
    trust_proxy: false,
    ignore_client_auth: false,
    real_ip_header: None,
    trusted_proxies: Vec::new(),
    admin_allowed_ips: Vec::new(),
    secure_cookies: false,
    require_hostname_bind: false,
    default_access: crate::settings::DefaultAccess::Allow,
    metrics_token: None,
    scaling_enabled: false,
    scaling_allow_http: false,
    scaling_allow_private: false,
    scaling_record_ttl: Duration::from_secs(3600),
    edge_token: None,
    edge_service_url: None,
    edge_entrypoints: Vec::new(),
    edge_cert_resolver: None,
    edge_include_offline: false,
    random_subdomain_suffix: None,
    client_down_threshold: Duration::from_secs(3600),
    tunnel_compression: false,
    custom_504_page: None,
    custom_503_page: None,
    lb_strategy: LbStrategy::RoundRobin,
    failover_mode: FailoverMode::Fail,
    failover_max_jumps: 2,
    failover_window: Duration::from_secs(15),
    failover_all_methods: false,
    retry_on_5xx: false,
    retry_statuses: Vec::new(),
    outlier_ejection: false,
    outlier_max_failures: 5,
    outlier_window: Duration::from_secs(30),
    outlier_eject: Duration::from_secs(30),
    cache_enabled: false,
    max_concurrent_requests: 100,
    max_ws_connections: 10_000,
    login_lockout_threshold: 5,
    login_lockout_secs: 60,
    audit_max_size: 10 * 1024 * 1024,
    audit_max_files: 3,
    ui_language: "en".to_string(),
    header_rules: Default::default(),
    static_routes: Default::default(),
    error_pages: Default::default(),
    route_limits: Default::default(),
    fallbacks: Default::default(),
    waf: Default::default(),
    maintenance_windows: Default::default(),
    alert_rules: Default::default(),
    denied_ips: Default::default(),
    identity_headers: false,
    visitor_identity_headers: false,
    access_log_sample_rate: 1.0,
    alternate_servers: Vec::new(),
    max_streams_per_ip: 0,
    otel_bridge: false,
    shutdown_drain: None,
    shutdown_drain_auto: false,
    shutdown_timeout: 10,
    request_id_enabled: true,
    request_id_header: "x-request-id".to_string(),
    request_id_trust_inbound: false,
    token_pinning: false,
    preview_noindex: false,
    cache_max_bytes: 64 * 1024 * 1024,
    cache_max_stale: 3600,
    stream_min_throughput: 0,
    stream_pause_bytes: 2 * 1024 * 1024,
    stream_resume_bytes: 512 * 1024,
    stream_backlog_limit: 16 * 1024 * 1024,
    outbound_policy: Default::default(),
  };

  let (client_connected_tx, _) = watch::channel(true);
  let state = Arc::new(AppState {
    clients: tokio::sync::RwLock::new(HashMap::new()),
    consumers: tokio::sync::Mutex::new(Default::default()),
    stream_counts: Arc::new(std::sync::Mutex::new(HashMap::new())),
    telemetry_tx: tokio::sync::mpsc::channel(1).0,
    pending_messages: Mutex::new(HashMap::new()),
    jwks_cache: Mutex::new(HashMap::new()),
    forward_auth_cache: Mutex::new(HashMap::new()),
    message_metrics: Default::default(),
    client_connected: client_connected_tx,
    connection_state: Mutex::new(ConnectionState {
      connected: true,
      last_disconnect: None,
    }),
    server_start_time: Instant::now(),
    pending_requests: Mutex::new(HashMap::new()),
    stats: Mutex::new(ServerStats {
      total_requests: 0,
      successful_requests: 0,
      failed_requests: 0,
      total_bytes_transferred: 0,
    }),
    recent_logs: Mutex::new(VecDeque::new()),
    traffic_tx: tokio::sync::broadcast::channel(16).0,
    events_tx: tokio::sync::broadcast::channel(16).0,
    config_store: std::sync::RwLock::new(Arc::new(config.clone())),
    config_env_defaults: Arc::new(config),
    settings_overrides: Mutex::new(SettingsOverrides::default()),
    settings_path: crate::test_support::test_temp_root()
      .join(format!("settings-{}.json", uuid::Uuid::new_v4())),
    dashboard_enabled: true,
    shutdown: watch::channel(false).0,
    active_proxied_requests: Arc::new(AtomicUsize::new(0)),
    active_ws_connections: Arc::new(AtomicUsize::new(0)),
    path_rr: Mutex::new(HashMap::new()),
    sessions: Mutex::new(test_session_store()),
    rate_limiter: Mutex::new(HashMap::new()),
    login_lockout: tokio::sync::Mutex::new(crate::auth::LockoutTracker::new(
      5,
      std::time::Duration::from_secs(60),
    )),
    token_rate: Mutex::new(HashMap::new()),
    token_daily_bytes: Mutex::new(HashMap::new()),
    token_seen_ips: Mutex::new(HashMap::new()),
    route_rate: Mutex::new(HashMap::new()),
    active_tunnel_count: AtomicUsize::new(0),
    ws_streams: Mutex::new(HashMap::new()),
    pending_upgrades: Mutex::new(HashMap::new()),
    token_store: Mutex::new(test_token_store()),
    admin_key_store: Mutex::new(test_admin_key_store()),
    inbox_store: Mutex::new(test_inbox_store()),
    users: Mutex::new(test_user_store()),
    response_streams: Mutex::new(HashMap::new()),
    captured_requests: Mutex::new(VecDeque::new()),
    audit: Mutex::new(test_audit_log()),
    persistent_stats: Mutex::new(test_stats_store()),
    webhook_deliveries: test_delivery_log(),
    scaling_store: Mutex::new(crate::test_support::test_scaling_store()),
    scaling_runtime: Mutex::new(crate::scaling::ScalingRuntime::default()),
    scaling_calls: crate::scaling::call_semaphore(),
    webhook_store: Mutex::new(test_webhook_store()),
    org_store: Mutex::new(test_org_store()),
    uptime: Mutex::new(test_uptime_store()),
    webauthn: None,
    webauthn_ceremonies: Mutex::new(crate::webauthn::WebauthnCeremonies::default()),
    oidc: None,
    org_oidc: Mutex::new(HashMap::new()),
    oidc_states: Mutex::new(HashMap::new()),
    tcp_streams: Mutex::new(HashMap::new()),
    udp_streams: Mutex::new(HashMap::new()),
    response_cache: Mutex::new(crate::cache::ResponseCache::default()),
    cache_inflight: std::sync::Mutex::new(std::collections::HashMap::new()),
    stage_stats: Mutex::new(crate::state::StageStats::default()),
    endpoint_stats: Mutex::new(crate::state::EndpointStats::default()),
    route_trends: Mutex::new(crate::state::RouteTrends::default()),
    activity: Mutex::new(crate::state::Activity::default()),
    maintenance: Mutex::new(std::collections::HashMap::new()),
    access_log: None,
    duration_histogram: DurationHistogram::default(),
    limit_counters: Default::default(),
  });

  let (tx_write, mut rx_write) = mpsc::channel::<Message>(100);
  let client_req_count = Arc::new(AtomicU64::new(0));

  state.clients.write().await.insert(
    "mock-client-1".to_string(),
    ClientHandle {
      drain_secs: None,
      tx: tx_write,
      disconnect: std::sync::Arc::new(tokio::sync::Notify::new()),
      connected_at: Instant::now(),
      client_ip: "127.0.0.1".to_string(),
      declared_client_id: None,
      last_ping_at: None,
      perms: ClientPerms::master(),
      draining: false,
      client_version: None,
      client_protocol: None,
      cpu_percent: None,
      rss_bytes: None,
      rtt_ms: None,
      jitter_ms: None,
      reconnects: None,
      reported_instance_id: None,
      instance_group: None,
      subscriptions: Vec::new(),
      services: vec![crate::state::ServiceState {
        metrics_labels: Vec::new(),
        service_custom_name: None,
        request_count: client_req_count,
        declared_path: None,
        assigned_path: None,
        declared_hostname: None,
        declared_hostnames: Vec::new(),
        assigned_hostnames: Vec::new(),
        random_hostname: None,
        override_path_bind: None,
        override_hostname_binds: Vec::new(),
        connections: None,
        connections_min: None,
        connections_max: None,
        capture: true,
        config_notes: Vec::new(),
        max_concurrent: None,
        max_concurrent_ceiling: None,
        inflight_limiter: None,
        admin_enabled: true,
        tcp_enabled: false,
        backend_healthy: true,
        backend_probed: true,
        priority: 0,
        bandwidth_bps: Arc::new(AtomicU64::new(0)),
        service_name: None,
        public: false,
        public_denied_warned: false,
        visitor_auth: None,
        visitor_auth_policy: None,
        visitor_auth_denied_warned: false,
        ungated_warned: false,
        allowed_ips: Vec::new(),
        allowed_ips_invalid_warned: false,
        scaling_invalid_warned: false,
        tunnels: Vec::new(),
        cache: false,
        cache_ignored_warned: false,
        resilience: false,
        max_request_body: None,
        response_timeout: None,
        webhook_inbox: false,
        denied: None,
        recent_failures: VecDeque::new(),
        ejected_until: None,
      }],
    },
  );

  let state_clone = state.clone();
  tokio::spawn(async move {
    if let Some(Message::Text(text)) = rx_write.recv().await
      && let Ok(TunnelMessage::Request { id, .. }) = serde_json::from_str::<TunnelMessage>(&text)
    {
      let mut pending = state_clone.pending_requests.lock().await;
      if let Some(req) = pending.remove(&id) {
        let headers = vec![("content-type".to_string(), "application/json".to_string())];
        let _ = req.tx.send(TunnelResponse {
          trailers: None,
          status: 200,
          headers,
          body: Some(base64::prelude::BASE64_STANDARD.encode(r#"{"status":"ok"}"#)),
          body_raw: None,
          stream_rx: None,
          timings: None,
        });
      }
    }
  });

  let response = proxy_handler(
    State(state),
    ConnectInfo(SocketAddr::from(([127, 0, 0, 1], 12345))),
    axum::extract::Request::new(Body::empty()),
  )
  .await;

  assert_eq!(response.status(), StatusCode::OK);
  assert_eq!(
    response
      .headers()
      .get("content-type")
      .unwrap()
      .to_str()
      .unwrap(),
    "application/json"
  );
}
